#Here are all word list, include level_words_list, interest_words_list and random_words_list

#Level_words_list
level_0_words = {
    "hei": "hello",
    "moi": "hi",
    "kiitos": "thank you",
    "anteeksi": "sorry",
    "kyllä": "yes",
    "ei": "no",
    "hyvä": "good",
    "hei hei": "bye",
    "nimi": "name",
    "minä": "I",
    "sinä": "you",
    "hän": "he/she",
    "vesi": "water",
    "ruoka": "food",
    "koti": "home",
    "koulu": "school",
    "ystävä": "friend",
    "perhe": "family",
    "koira": "dog",
    "kissa": "cat"
}

level_a1_words = {
    "aamu": "morning",
    "ilta": "evening",
    "yö": "night",
    "päivä": "day",
    "tänään": "today",
    "huomenna": "tomorrow",
    "eilen": "yesterday",
    "nyt": "now",
    "talo": "house",
    "kauppa": "shop",
    "kaupunki": "city",
    "työ": "work",
    "opiskelija": "student",
    "opettaja": "teacher",
    "kirja": "book",
    "kahvi": "coffee",
    "tee": "tea",
    "maito": "milk",
    "mennä": "to go",
    "tulla": "to come"
}

level_a2_words = {
    "matka": "trip",
    "loma": "holiday",
    "asema": "station",
    "juna": "train",
    "bussi": "bus",
    "lippu": "ticket",
    "ravintola": "restaurant",
    "aamiainen": "breakfast",
    "illallinen": "dinner",
    "sää": "weather",
    "aurinko": "sun",
    "sade": "rain",
    "ystävällinen": "friendly",
    "onnellinen": "happy",
    "surullinen": "sad",
    "väsynyt": "tired",
    "tarvita": "to need",
    "haluta": "to want",
    "ymmärtää": "to understand",
    "muistaa": "to remember"
}

level_b1_words = {
    "mahdollisuus": "possibility",
    "kokemus": "experience",
    "mielipide": "opinion",
    "päätös": "decision",
    "tavoite": "goal",
    "ongelma": "problem",
    "ratkaisu": "solution",
    "ympäristö": "environment",
    "yhteiskunta": "society",
    "koulutus": "education",
    "terveys": "health",
    "tulevaisuus": "future",
    "menneisyys": "past",
    "suhde": "relationship",
    "muutos": "change",
    "vaikutus": "effect",
    "onnistua": "to succeed",
    "kehittää": "to develop",
    "päättää": "to decide",
    "verrata": "to compare"
}

level_b2_words = {
    "vastuu": "responsibility",
    "merkitys": "meaning / significance",
    "näkökulma": "perspective",
    "periaate": "principle",
    "ilmiö": "phenomenon",
    "kehitys": "development",
    "vaikutusvalta": "influence / power",
    "päätöksenteko": "decision-making",
    "mahdollisuus": "opportunity / possibility",
    "haaste": "challenge",
    "ratkaista": "to solve",
    "arvioida": "to evaluate",
    "perustella": "to justify",
    "ehdottaa": "to suggest",
    "saavuttaa": "to achieve",
    "edistää": "to promote",
    "osallistua": "to participate",
    "suunnitella": "to plan",
    "vaatia": "to require",
    "vaikuttaa": "to influence"
}

# Interest_words_list
nature_words = {
    "metsä": "forest",
    "järvi": "lake",
    "meri": "sea",
    "joki": "river",
    "vuori": "mountain",
    "saari": "island",
    "puu": "tree",
    "kukka": "flower",
    "ruoho": "grass",
    "kasvi": "plant",
    "eläin": "animal",
    "lintu": "bird",
    "karhu": "bear",
    "susi": "wolf",
    "kettu": "fox",
    "hirvi": "moose",
    "aurinko": "sun",
    "kuu": "moon",
    "pilvi": "cloud",
    "sade": "rain"
}

life_words = {
    "aamu": "morning",
    "ilta": "evening",
    "viikko": "week",
    "viikonloppu": "weekend",
    "koti": "home",
    "perhe": "family",
    "ystävä": "friend",
    "koulu": "school",
    "työ": "work",
    "opiskelu": "studying",
    "kauppa": "shop",
    "bussi": "bus",
    "juna": "train",
    "asema": "station",
    "puhelin": "phone",
    "tietokone": "computer",
    "kirja": "book",
    "avain": "key",
    "raha": "money",
    "aika": "time"
}

food_words = {
    "leipä": "bread",
    "juusto": "cheese",
    "muna": "egg",
    "liha": "meat",
    "kana": "chicken",
    "kala": "fish",
    "riisi": "rice",
    "peruna": "potato",
    "porkkana": "carrot",
    "omena": "apple",
    "banaani": "banana",
    "mansikka": "strawberry",
    "maito": "milk",
    "vesi": "water",
    "kahvi": "coffee",
    "tee": "tea",
    "mehu": "juice",
    "keitto": "soup",
    "salaatti": "salad",
    "kakku": "cake"
}

culture_words = {
    "musiikki": "music",
    "elokuva": "movie",
    "teatteri": "theatre",
    "taide": "art",
    "maalaus": "painting",
    "kirjallisuus": "literature",
    "kirja": "book",
    "laulu": "song",
    "tanssi": "dance",
    "juhla": "celebration",
    "festivaali": "festival",
    "perinne": "tradition",
    "historia": "history",
    "museo": "museum",
    "näyttely": "exhibition",
    "näyttelijä": "actor",
    "kirjailija": "writer",
    "taiteilija": "artist",
    "soitin": "musical instrument",
    "kieli": "language"
}

sports_words = {
    "jalkapallo": "football",
    "jääkiekko": "ice hockey",
    "koripallo": "basketball",
    "tennis": "tennis",
    "uinti": "swimming",
    "juoksu": "running",
    "hiihto": "skiing",
    "luistelu": "skating",
    "pyöräily": "cycling",
    "voimistelu": "gymnastics",
    "golf": "golf",
    "pallo": "ball",
    "joukkue": "team",
    "pelaaja": "player",
    "valmentaja": "coach",
    "kilpailu": "competition",
    "ottelu": "match",
    "maali": "goal",
    "voitto": "victory",
    "harjoitus": "training"
}

#random_words_list
random_words = {
    "ystävä": "friend",
    "vesi": "water",
    "aamu": "morning",
    "kaupunki": "city",
    "kirja": "book",
    "matka": "trip",
    "aurinko": "sun",
    "perhe": "family",
    "ravintola": "restaurant",
    "juna": "train",
    "metsä": "forest",
    "kahvi": "coffee",
    "onnellinen": "happy",
    "koulu": "school",
    "lippu": "ticket",
    "järvi": "lake",
    "ystävällinen": "friendly",
    "musiikki": "music",
    "joukkue": "team",
    "tavoite": "goal",
    "ympäristö": "environment",
    "koti": "home",
    "juhla": "celebration",
    "perinne": "tradition",
    "harjoitus": "training",
    "mahdollisuus": "possibility",
    "kehittää": "to develop",
    "vastuu": "responsibility",
    "saavuttaa": "to achieve",
    "näkökulma": "perspective"
}